version: '3.8'
services:
  # MS SQL Server - for Windows/Intel
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "YourStrongPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    restart: unless-stopped
    volumes:
      - sqlserver_data:/var/opt/mssql
      - sqlserver_log:/var/opt/mssql/log
    user: "0:0"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: API/Dockerfile
    container_name: backend
    depends_on:
      - sqlserver
      - kafka
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrderManagement;User Id=sa;Password=YourStrongPassword123;TrustServerCertificate=true;
      - JWT__SecretKey=YourSuperSecretKeyHereThatIsAtLeast32CharactersLong
      - JWT__Issuer=YourApp
      - JWT__Audience=YourApp
      - JWT__ExpirationMinutes=60
      - Kafka__BootstrapServers=kafka:29092
    restart: unless-stopped

  # Worker service for background processing
  worker:
    build:
      context: ./backend
      dockerfile: Worker/Dockerfile
    container_name: worker
    depends_on:
      - sqlserver
      - kafka
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=OrderManagement;User Id=sa;Password=YourStrongPassword123;TrustServerCertificate=true;
      - Kafka__BootstrapServers=kafka:29092
    restart: unless-stopped

  # Frontend Angular application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlserver_data:
  sqlserver_log: 